services:
  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
      POSTGRES_DB: bookstore_dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookstore_dev"]
      interval: 5s
      timeout: 5s
      retries: 10
    # Se quiser expor pra host: descomente
    # ports:
    #   - "5435:5432"

  web:
    build:
      context: .
      target: runtime
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./env.prod
    networks:
      - backend
    volumes:
      - app_static:/app/staticfiles
      - app_media:/app/media
    expose:
      - "8000"
    # (não publique porta; somente Nginx expõe 80)

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app_static:/static:ro
      - app_media:/media:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  app_static:
  app_media:
