services:
  db:
    image: postgres:16.3-alpine
    ports:
      - "5435:5436"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
      POSTGRES_DB: bookstore_dev_db
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookstore_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app
    ports:
      - "80:8000"
    env_file:
      - ./env.dev
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  app_data: