services:
  - type: web
    name: bookstore
    runtime: python
    buildCommand: "poetry install"
    startCommand: "poetry run gunicorn bookstore.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: bookstore-api-ueva.onrender.com 127.0.0.1 localhost
      - key: SQL_ENGINE
        value: django.db.backends.postgresql
      - key: SQL_DATABASE
        sync: false
      - key: SQL_USER
        sync: false
      - key: SQL_PASSWORD
        sync: false
      - key: SQL_HOST
        sync: false
      - key: SQL_PORT
        value: "5432"
