name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16  # Escolha a versão do PostgreSQL conforme sua necessidade
        ports:
          - 5432:5432  # O PostgreSQL usará a porta 5432
        env:
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
          POSTGRES_DB: bookstore_dev_db
        options: --health-cmd "pg_isready -U bookstore_dev" --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Install dependencies
        run: poetry install

      - name: Set DATABASE_URL environment variable
        run: echo "DATABASE_URL=postgresql://bookstore_dev:bookstore_dev@localhost:5432/bookstore_dev_db" >> $GITHUB_ENV

      - name: Run Django tests
        run: poetry run python manage.py test

      - name: Lint with wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

