name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Install dependencies
        run: poetry install

      - name: Set DATABASE_URL environment variable
        run: echo "DATABASE_URL=postgresql://bookstore_dev:Q3w61u0DDy8zDBAxw7yQSY16reuZnnUQ@dpg-d1sg16ndiees73fi9t50-a.oregon-postgres.render.com/bookstore_dev_db_s7d4" >> $GITHUB_ENV

      - name: Run Django tests
        run: poetry run python manage.py test

      - name: Lint with wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


